# Wrangler configuration for Cloudflare Pages
name = "avone"
compatibility_date = "2024-01-01"

# Pages-specific configuration
pages_build_output_dir = "deploy"

[build]
command = ""
cwd = ""

[build.upload]
format = "directory"
dir = "deploy"